### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by nl6720** [erofs/docs#2]
This repo lacks a license.

**Comment by hsiangkao** [comment]
Which license do you perfer? btw? :-)

**Comment by nl6720** [comment]
Since it's documentation, a Creative Commons license (`CC-BY-SA-4.0` perhaps) seems appropriate unless it needs to be compatible with the license of erofs-utils.

**Comment by hsiangkao** [comment]
> Since it's documentation, a Creative Commons license (`CC-BY-SA-4.0` perhaps) seems appropriate unless it needs to be compatible with the license of erofs-utils.

Okay, thanks! let me revise the license later.
